// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzyKm_hcFmhC20AtW-pdpQdGNwEa8E504',
    appId: '1:755522027500:web:dd8e7900e1a0dda5720ac9',
    messagingSenderId: '755522027500',
    projectId: 'narcimages',
    authDomain: 'narcimages.firebaseapp.com',
    storageBucket: 'narcimages.appspot.com',
    measurementId: 'G-96ZWM4SLQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz42ZzlSNTEHZ8RbxynKtN9M88R01kqjY',
    appId: '1:755522027500:android:8b371a45953eaf78720ac9',
    messagingSenderId: '755522027500',
    projectId: 'narcimages',
    storageBucket: 'narcimages.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg1Ai672s4iNmmlFLuKkPurSRBdVFqdc4',
    appId: '1:755522027500:ios:2344d12bdcfdce89720ac9',
    messagingSenderId: '755522027500',
    projectId: 'narcimages',
    storageBucket: 'narcimages.appspot.com',
    iosClientId: '755522027500-b6s7j05rftck6i7k41cv2dh9s8eheo2j.apps.googleusercontent.com',
    iosBundleId: 'tn.narc.narcsecond',
  );
}
